# commit to be tagged for the new release
commit = "HEAD"

project_name = "talos-metal-agent"
github_repo = "siderolabs/talos-metal-agent"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
